"""
Configuration package for NIDS
"""

from .config import (
    KAFKA_CONFIG,
    SPARK_CONFIG,
    MONGODB_CONFIG,
    MODEL_PATHS,
    FEATURE_CONFIG,
    UNSW_FEATURE_CONFIG,
    ATTACK_TYPE_MAPPING,
    STREAMING_CONFIG,
    ALERT_CONFIG,
    PRODUCER_CONFIG,
    BASE_DIR,
    DATA_DIR,
    MODELS_DIR,
)

from .scaler_paths import SCALER_PATHS, MODEL_PATHS as DATASET_MODEL_PATHS

__all__ = [
    "KAFKA_CONFIG",
    "SPARK_CONFIG", 
    "MONGODB_CONFIG",
    "MODEL_PATHS",
    "FEATURE_CONFIG",
    "UNSW_FEATURE_CONFIG",
    "ATTACK_TYPE_MAPPING",
    "STREAMING_CONFIG",
    "ALERT_CONFIG",
    "PRODUCER_CONFIG",
    "BASE_DIR",
    "DATA_DIR",
    "MODELS_DIR",
    "SCALER_PATHS",
    "DATASET_MODEL_PATHS",
]
